
####################################################################################
# Generated by Vivado 2025.2 built on 'Fri Nov 14 19:35:11 GMT 2025' by 'xbuild'
# Command Used: write_xdc -force E:/nf/all_100_v1/N3/routed_reports/effective.xdc
####################################################################################


####################################################################################
# Constraints from file : 'network.xdc'
####################################################################################

create_clock -period 10.000 -name core_clk [get_ports clk]


# User Generated XDC timing constraints 

set _xlnx_shared_i0 [get_ports -filter {DIRECTION == IN && NAME != clk}]
set_input_delay -clock [get_clocks core_clk] -reference_pin [get_pins -quiet rst_q_reg/C] -min 0.200 $_xlnx_shared_i0
set_input_delay -clock [get_clocks core_clk] -reference_pin [get_pins -quiet rst_q_reg/C] -max 1.000 $_xlnx_shared_i0
set_output_delay -clock [get_clocks core_clk] -reference_pin [get_pins -quiet rst_q_reg/C] -min -0.100 [get_ports -filter {DIRECTION == OUT}]
set_output_delay -clock [get_clocks core_clk] -reference_pin [get_pins -quiet rst_q_reg/C] -max 1.000 [get_ports -filter {DIRECTION == OUT}]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
